# Generated by Django 3.1.4 on 2020-12-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20201217_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('union', 'Union Libre'), ('viudo', 'Viudo'), ('separado', 'Separado'), ('soltero', 'Soltero'), ('divorciado', 'Divorciado'), ('casado', 'Casado')], default='soltero', max_length=30),
        ),
    ]
