# Generated by Django 3.1.4 on 2021-01-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20201217_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('separado', 'Separado'), ('viudo', 'Viudo'), ('union', 'Union Libre'), ('divorciado', 'Divorciado'), ('soltero', 'Soltero'), ('casado', 'Casado')], default='soltero', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='femenino', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('deposito', 'Deposito'), ('retiro', 'Retiro')], default='deposito', max_length=30),
        ),
    ]
