# Generated by Django 3.1.4 on 2021-01-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_auto_20210105_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('casado', 'Casado'), ('soltero', 'Soltero'), ('divorciado', 'Divorciado'), ('union', 'Union Libre'), ('separado', 'Separado'), ('viudo', 'Viudo')], default='soltero', max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=30),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipoCuenta',
            field=models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente'), ('programado', 'Programado')], default='ahorros', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Deposito')], default='deposito', max_length=30),
        ),
    ]
